//
// Generated file, do not edit! Created by opp_msgtool 6.0 from plexe/messages/InterferingBeacon.msg.
//

#ifndef __INTERFERINGBEACON_M_H
#define __INTERFERINGBEACON_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif

class InterferingBeacon;
/**
 * Class generated from <tt>plexe/messages/InterferingBeacon.msg:21</tt> by opp_msgtool.
 * <pre>
 * packet InterferingBeacon
 * {
 * }
 * </pre>
 */
class PLEXE_API InterferingBeacon : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const InterferingBeacon& other);

  protected:
    bool operator==(const InterferingBeacon&) = delete;

  public:
    InterferingBeacon(const char *name=nullptr, short kind=0);
    InterferingBeacon(const InterferingBeacon& other);
    virtual ~InterferingBeacon();
    InterferingBeacon& operator=(const InterferingBeacon& other);
    virtual InterferingBeacon *dup() const override {return new InterferingBeacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const InterferingBeacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, InterferingBeacon& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline InterferingBeacon *fromAnyPtr(any_ptr ptr) { return check_and_cast<InterferingBeacon*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INTERFERINGBEACON_M_H

