//
// Generated file, do not edit! Created by opp_msgtool 6.0 from plexe/messages/JoinFormationAck.msg.
//

#ifndef __JOINFORMATIONACK_M_H
#define __JOINFORMATIONACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif

class JoinFormationAck;
#include "ManeuverMessage_m.h" // import ManeuverMessage

/**
 * Class generated from <tt>plexe/messages/JoinFormationAck.msg:27</tt> by opp_msgtool.
 * <pre>
 * // Response to a JoinPlatoon.
 * // Is sent from the joiner to the leader of the Platoon.
 * // Confirms the joiner joined the Platoon successful at the given position.
 * packet JoinFormationAck extends ManeuverMessage
 * {
 *     double platoonSpeed;
 *     int platoonLane;
 *     int newPlatoonFormation[];
 * }
 * </pre>
 */
class PLEXE_API JoinFormationAck : public ::ManeuverMessage
{
  protected:
    double platoonSpeed = 0;
    int platoonLane = 0;
    int *newPlatoonFormation = nullptr;
    size_t newPlatoonFormation_arraysize = 0;

  private:
    void copy(const JoinFormationAck& other);

  protected:
    bool operator==(const JoinFormationAck&) = delete;

  public:
    JoinFormationAck(const char *name=nullptr, short kind=0);
    JoinFormationAck(const JoinFormationAck& other);
    virtual ~JoinFormationAck();
    JoinFormationAck& operator=(const JoinFormationAck& other);
    virtual JoinFormationAck *dup() const override {return new JoinFormationAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getPlatoonSpeed() const;
    virtual void setPlatoonSpeed(double platoonSpeed);

    virtual int getPlatoonLane() const;
    virtual void setPlatoonLane(int platoonLane);

    virtual void setNewPlatoonFormationArraySize(size_t size);
    virtual size_t getNewPlatoonFormationArraySize() const;
    virtual int getNewPlatoonFormation(size_t k) const;
    virtual void setNewPlatoonFormation(size_t k, int newPlatoonFormation);
    virtual void insertNewPlatoonFormation(size_t k, int newPlatoonFormation);
    [[deprecated]] void insertNewPlatoonFormation(int newPlatoonFormation) {appendNewPlatoonFormation(newPlatoonFormation);}
    virtual void appendNewPlatoonFormation(int newPlatoonFormation);
    virtual void eraseNewPlatoonFormation(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const JoinFormationAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, JoinFormationAck& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline JoinFormationAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<JoinFormationAck*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __JOINFORMATIONACK_M_H

