//
// Generated file, do not edit! Created by opp_msgtool 6.0 from plexe/messages/JoinFormation.msg.
//

#ifndef __JOINFORMATION_M_H
#define __JOINFORMATION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif

class JoinFormation;
#include "ManeuverMessage_m.h" // import ManeuverMessage

/**
 * Class generated from <tt>plexe/messages/JoinFormation.msg:27</tt> by opp_msgtool.
 * <pre>
 * // Request to actually join the Platoon.
 * // Is sent from the leader of the Platoon to the joiner.
 * // Again contains the position the joiner should join.
 * packet JoinFormation extends ManeuverMessage
 * {
 *     double platoonSpeed;
 *     int platoonLane;
 *     int newPlatoonFormation[];
 * }
 * </pre>
 */
class PLEXE_API JoinFormation : public ::ManeuverMessage
{
  protected:
    double platoonSpeed = 0;
    int platoonLane = 0;
    int *newPlatoonFormation = nullptr;
    size_t newPlatoonFormation_arraysize = 0;

  private:
    void copy(const JoinFormation& other);

  protected:
    bool operator==(const JoinFormation&) = delete;

  public:
    JoinFormation(const char *name=nullptr, short kind=0);
    JoinFormation(const JoinFormation& other);
    virtual ~JoinFormation();
    JoinFormation& operator=(const JoinFormation& other);
    virtual JoinFormation *dup() const override {return new JoinFormation(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getPlatoonSpeed() const;
    virtual void setPlatoonSpeed(double platoonSpeed);

    virtual int getPlatoonLane() const;
    virtual void setPlatoonLane(int platoonLane);

    virtual void setNewPlatoonFormationArraySize(size_t size);
    virtual size_t getNewPlatoonFormationArraySize() const;
    virtual int getNewPlatoonFormation(size_t k) const;
    virtual void setNewPlatoonFormation(size_t k, int newPlatoonFormation);
    virtual void insertNewPlatoonFormation(size_t k, int newPlatoonFormation);
    [[deprecated]] void insertNewPlatoonFormation(int newPlatoonFormation) {appendNewPlatoonFormation(newPlatoonFormation);}
    virtual void appendNewPlatoonFormation(int newPlatoonFormation);
    virtual void eraseNewPlatoonFormation(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const JoinFormation& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, JoinFormation& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline JoinFormation *fromAnyPtr(any_ptr ptr) { return check_and_cast<JoinFormation*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __JOINFORMATION_M_H

